-- Sample companies for JobHunt application
-- These companies can be inserted directly into database without user constraints

INSERT INTO companies (
    name, 
    email, 
    phone_number, 
    website_url, 
    establishment_year, 
    team_size, 
    industry_type, 
    about, 
    country, 
    city, 
    address, 
    tax_id, 
    logo_url,
    cover_url,
    active,
    created_at,
    updated_at
) VALUES 
(
    'TechCorp Vietnam',
    'hr@techcorp.vn',
    '0248888888',
    'https://techcorp.vn',
    2015,
    '100-500',
    'Technology',
    'TechCorp is a leading technology company in Vietnam, specializing in software development, mobile applications, and digital transformation solutions.',
    'Vietnam',
    'Ho Chi Minh City',
    '123 Nguyen Hue Street, District 1, Ho Chi Minh City',
    '0123456789',
    'https://example.com/logos/techcorp.png',
    'https://example.com/covers/techcorp.jpg',
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'VN Bank Solutions',
    'careers@vnbank.com.vn',
    '0247777777',
    'https://vnbank.com.vn',
    2010,
    '500-1000',
    'Banking & Finance',
    'VN Bank Solutions provides comprehensive financial services and banking solutions across Vietnam with cutting-edge technology.',
    'Vietnam',
    'Hanoi',
    '456 Ba Trieu Street, Hai Ba Trung District, Hanoi',
    '0987654321',
    'https://example.com/logos/vnbank.png',
    'https://example.com/covers/vnbank.jpg',
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'EduViet Learning',
    'jobs@eduviet.edu.vn',
    '0246666666',
    'https://eduviet.edu.vn',
    2018,
    '50-100',
    'Education',
    'EduViet Learning is an innovative education technology company providing online learning platforms and educational content.',
    'Vietnam',
    'Da Nang',
    '789 Le Duan Street, Hai Chau District, Da Nang',
    '0111222333',
    'https://example.com/logos/eduviet.png',
    'https://example.com/covers/eduviet.jpg',
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'HealthCare Plus',
    'recruitment@healthcareplus.vn',
    '0245555555',
    'https://healthcareplus.vn',
    2012,
    '200-500',
    'Healthcare',
    'HealthCare Plus is a leading healthcare provider in Vietnam, offering modern medical services and telemedicine solutions.',
    'Vietnam',
    'Ho Chi Minh City',
    '321 Dong Khoi Street, District 1, Ho Chi Minh City',
    '0444555666',
    'https://example.com/logos/healthcare.png',
    'https://example.com/covers/healthcare.jpg',
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    'Green Energy Co.',
    'hr@greenenergy.vn',
    '0244444444',
    'https://greenenergy.vn',
    2020,
    '20-50',
    'Energy & Environment',
    'Green Energy Co. focuses on renewable energy solutions and environmental sustainability projects across Southeast Asia.',
    'Vietnam',
    'Hanoi',
    '654 Tran Hung Dao Street, Hoan Kiem District, Hanoi',
    '0777888999',
    'https://example.com/logos/greenenergy.png',
    'https://example.com/covers/greenenergy.jpg',
    true,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
); 