server:
  port: 8080
  servlet:
    context-path: /profile

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/jobhunt
    username: jobhunt
    password: jobhunt
    driverClassName: org.postgresql.Driver
  security:
    oauth2:
      resource server:
        jwt:  
          issuer-uri: http://localhost:8180/realms/jobhunt
          jwk-set-uri: http://localhost:8180/realms/jobhunt/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://localhost:8180
  realm: jobhunt
  resource: jobhunt
  public-client: false
  principal-attribute: preferred_username
  ssl-required: external
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}
  connection-pool-size: 10
  connection-timeout: 5000
  read-timeout: 5000

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity-time: 3600
  refresh-token-validity-time: 86400

cloudflare:
  r2:
    access:
      key:
        id: ${CLOUDFLARE_R2_ACCESS_KEY}
    secret:
      access:
        key: ${CLOUDFLARE_R2_SECRET_KEY}
    endpoint: ${CLOUDFLARE_R2_ENDPOINT}
    bucket: ${CLOUDFLARE_R2_BUCKET_NAME}
    region: auto

app:
  cookie:
    domain: # Leave empty for localhost development
    secure: false
    httpOnly: true
    accessToken:
      expiration: 3600
    refreshToken:
      expiration: 86400

# Debug logging
logging:
  level:
    com.jobhunt.config.CookieAuthenticationFilter: DEBUG
    com.jobhunt.service.impl.AuthServiceImpl: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
    org.springframework.security.oauth2.server.resource: DEBUG